version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: banking_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bini@1221
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # We'll add Kafka/RabbitMQ here in Phase 3

volumes:
  postgres_data: