spring.application.name=bank-app
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bini@1221}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
app.jwt-secret=${APP_JWT_SECRET:3cfa31934c9f1311542f7ee085f1c911361c47012306f6630f14659b854e4df5}
app.jwt-expiration-milliseconds=${APP_JWT_EXPIRATION_MILLISECONDS:300000}
app.jwt-refresh-expiration-milliseconds=${APP_JWT_REFRESH_EXPIRATION_MILLISECONDS:604800000}
