spring.application.name=bank-app
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=admin
spring.datasource.password=bini@1221
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt-secret=3cfa31934c9f1311542f7ee085f1c911361c47012306f6630f14659b854e4df5
app.jwt-expiration-milliseconds=300000
app.jwt-refresh-expiration-milliseconds=604800000

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.transaction-topic=transaction-events
spring.kafka.consumer.group-id=banking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
